// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RaspberryPuppy.EFDbContext;

#nullable disable

namespace RaspberryPuppy.Migrations
{
    [DbContext(typeof(PuppyDbContext))]
    [Migration("20241205135521_Puppy1")]
    partial class Puppy1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RaspberryPuppy.Personality", b =>
                {
                    b.Property<int>("TagNr")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Race")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Temperament")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TagNr");

                    b.ToTable("Personalities");
                });

            modelBuilder.Entity("RaspberryPuppy.TripData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PersonalityTagNr")
                        .HasColumnType("int");

                    b.Property<int>("TagNr")
                        .HasColumnType("int");

                    b.Property<int>("Temperature")
                        .HasColumnType("int");

                    b.Property<int>("TimeOutside")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonalityTagNr");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("RaspberryPuppy.TripData", b =>
                {
                    b.HasOne("RaspberryPuppy.Personality", "Personality")
                        .WithMany()
                        .HasForeignKey("PersonalityTagNr")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personality");
                });
#pragma warning restore 612, 618
        }
    }
}
